# Generated by Django 4.1.1 on 2022-10-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0002_remove_doctor_first_name_remove_doctor_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default='dm', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='Коновалов', max_length=32),
            preserve_default=False,
        ),
    ]
