# Generated by Django 4.1.1 on 2022-10-10 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0004_ward_alter_doctor_speciality_patient_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(default=datetime.date(1999, 12, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
