# Generated by Django 4.1.1 on 2022-10-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0009_doctor_photo_alter_case_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.FilePathField(),
        ),
    ]
