# Generated by Django 4.1.2 on 2022-10-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0010_alter_doctor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/photos/'),
        ),
    ]
