# Generated by Django 4.1.1 on 2022-10-23 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0011_alter_doctor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hire_date',
            field=models.DateField(default=datetime.date(1980, 10, 10)),
            preserve_default=False,
        ),
    ]
