# Generated by Django 4.1.1 on 2022-10-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0012_doctor_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='description',
            field=models.TextField(default='desc'),
            preserve_default=False,
        ),
    ]
